# NumPy fundamentals

In [1]:
import numpy as np

## Array Basics

In [2]:
fruits = ["apple", "banana", "cherry", "date"]

In [4]:
arr_1 = np.array(fruits)

In [5]:
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [6]:
print(arr_1.dtype)

<U6


In [7]:
# The U means unicode and the 6 is the max string out of all the fruits individually

In [8]:
arr_2 = np.array([[10,11,12],[13,14,15]])

In [9]:
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [11]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [12]:
# The transpose didn't change the value it just listed it a different way

In [14]:
arr_3 = np.array([[1,3,5],[2,4,6]])

In [15]:
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [16]:
arr_4 = np.array([arr_3[0,2],arr_3[1,1]])

In [17]:
print(arr_4)

[5 4]


In [18]:
arr_5 = np.ones((2,2,2), dtype=int)

In [19]:
print(arr_5)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
