# Exercise 1.A NumPy: Manipulating Arrays

In [3]:
import numpy as np 

## Looping Through Arrays

In [4]:
arrA = np.array([[11,12,13],[14,15,16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [5]:
for x in arrA:
    print(x*2)

[22 24 26]
[28 30 32]


In [6]:
for x in arrA:
    for y in x:
        print(y*2)

22
24
26
28
30
32


### The first loop is going horizontal like on a x axis and the second loop is coming out vertical like on a y axis 

In [7]:
loop_result = x * 2
for x in arrA:
    for y in x:
        print(x*2) # this just repeated the result 2 more times

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [8]:
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [9]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [10]:
stacked_array_1 = np.concatenate((joined_array_1, joined_array_1))
print(stacked_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [12]:
# stacked_array_2 = np.concatenate((joined_array_1, joined_array_2))
# print(stacked_array_2) # there was a error because they don't match

In [13]:
another_joined_array = np.concatenate((joined_array_1,arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [15]:
another_2 = np.concatenate((joined_array_1,joined_array_1), axis=1)
print(another_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]
 [11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [18]:
h = np.hstack((arrA, arrA))
v = np.vstack((arrA, arrA))
d = np.dstack((arrA, arrA))

print(h)
print(v)
print(d)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [20]:
splitsky = np.split(joined_array_1, 2)
print(splitsky) # theres 2 arrays

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [22]:
# spliterino = np.split(joined_array_1, 3)
# print(spliterino)
# error says can't equally split

## Searching and Replacing Array Values

In [24]:
result_1 = np.where(arrA % 2 == 0, arrA, "odd")
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [27]:
arrB = np.array([[7,6],[13,5],[7,3]])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [28]:
print(arrB)

[[ 7  6]
 [13  5]
 [ 7  3]]


In [29]:
z = arrB < 7

In [30]:
arrC = arrB[z]
print(arrC)

[6 5 3]


In [31]:
y = arrB >= 7 

In [32]:
arrD = arrB[y]
print(arrD)

[ 7 13  7]
