# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [2]:
r_1 = np.random.randint(1,21, size=2)
print(r_1)

[ 6 16]


In [3]:
r_2 = np.random.randint(1,21, size=(1,2))
print(r_2)

[[14 11]]


In [5]:
r_3 = np.random.rand(2,1)
print(r_3)

[[0.82010169]
 [0.32672983]]


In [6]:
r_4 = np.random.randint(20,101, size=(4,5))
print(r_4)

[[35 64 88 67 31]
 [65 59 27 32 79]
 [36 97 24 33 51]
 [59 80 20 23 50]]


In [7]:
r_5 = np.random.rand(4,5)
print(r_5)

[[0.28277512 0.0054369  0.10273621 0.07540444 0.16249005]
 [0.44976238 0.28696792 0.44355745 0.46307825 0.55313464]
 [0.94162503 0.72721256 0.42319442 0.99927299 0.32450894]
 [0.83293671 0.69429092 0.97691368 0.55601147 0.60192995]]


## Generating Random Choices from an Array

In [8]:
students = np.array(["Julissa","Longley","Angel","David","Tracy","Shay","El","Onur","Fuat","Maritza","Jimmy","Paul"])
print(students)

['Julissa' 'Longley' 'Angel' 'David' 'Tracy' 'Shay' 'El' 'Onur' 'Fuat'
 'Maritza' 'Jimmy' 'Paul']


In [19]:
call_on = np.random.choice(students)
print(call_on)

Onur


In [21]:
breakout_groups = np.random.choice(students, size =(3,4))
print(breakout_groups) #I don't think this would be effective because it repeats names

[['Julissa' 'Tracy' 'Fuat' 'Onur']
 ['Tracy' 'David' 'David' 'Maritza']
 ['Angel' 'Paul' 'Tracy' 'Jimmy']]


In [27]:
p_val = [0,0.03,0.04,0.05,0.06,0.07,0.07,0.08,0.10,0.10,0.10,0.30]
call_on_weighted = np.random.choice(students, size=5, p=p_val)
print(call_on_weighted) # I did the p_vals like that because everytime I got a error that they need to add to 1.00

['Shay' 'Paul' 'Tracy' 'Jimmy' 'El']


 ## Generating a Normal Distribution

In [28]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4,5))
print(bell_curve)

[[14.21154213  8.77103708  5.85734716  6.0073701   1.51292138]
 [17.28685591 10.12863426 13.34048863 15.49417886 11.11041377]
 [ 5.33224375  4.85296373 11.36261864 13.12223722  5.87683109]
 [16.01911542 20.04665179  8.6406699  11.2693648  26.48240573]]
