# Exercise 1.C Performing operations on arrays

In [2]:
import numpy as np

## Sample Arrays

In [3]:
r_1 = np.random.randint(1,21, size=2)
r_2 = np.random.randint(1,21, size=(1,2))
r_3 = np.random.rand(2,1)
r_4 = np.random.randint(20,101, size=(4,5))
r_5 = np.random.rand(4,5)

## Permutations

In [4]:
print(r_4)

[[57 82 77 77 63]
 [77 25 59 59 56]
 [79 42 63 24 38]
 [28 89 88 84 54]]


In [5]:
np.random.shuffle(r_4)

In [6]:
print(r_4)

[[28 89 88 84 54]
 [77 25 59 59 56]
 [79 42 63 24 38]
 [57 82 77 77 63]]


It switched row 0 and row 2 with each other ^

In [7]:
new_shuffle = np.random.permutation(r_4)

In [8]:
print(r_4)

[[28 89 88 84 54]
 [77 25 59 59 56]
 [79 42 63 24 38]
 [57 82 77 77 63]]


from what I see permutation makes a copy while shuffle actually shuffles

## Mathematical Operations

In [9]:
print(r_1.shape)
print(r_2.shape)

(2,)
(1, 2)


In [10]:
print(np.add(r_1.shape,r_2.shape))

[3 4]


In [11]:
print(r_1.shape)
print(r_3.shape)

(2,)
(2, 1)


In [12]:
print(np.add(r_1.shape,r_3.shape))

[4 3]


In [13]:
print(r_2.shape)
print(r_4.shape)

(1, 2)
(4, 5)


In [14]:
print(np.add(r_2.shape,r_4.shape))

[5 7]


In [15]:
print(np.add(r_1.shape,r_4.shape)) # this worked no error

[6 7]


In [16]:
print(np.add(r_2.shape,r_3.shape)) # this also worked no error

[3 3]


In [17]:
print(np.add(r_3.shape,r_4.shape)) # this worked too

[6 6]


In [18]:
print(np.array([1]) + r_4)

[[29 90 89 85 55]
 [78 26 60 60 57]
 [80 43 64 25 39]
 [58 83 78 78 64]]


In [19]:
print(np.array([[1]]) + r_4)

[[29 90 89 85 55]
 [78 26 60 60 57]
 [80 43 64 25 39]
 [58 83 78 78 64]]


In [20]:
print(np.array([1,1,1,1,1]) + r_4)

[[29 90 89 85 55]
 [78 26 60 60 57]
 [80 43 64 25 39]
 [58 83 78 78 64]]


In [21]:
# print(np.array([[1],[1]]) + r_4) / #the error says operands could not be broadcast together with shapes (2,1) (4,5)

My idea is that broadcasting only works if the numbers are compatible

## Rounding

In [22]:
print(r_3)

[[0.7373165 ]
 [0.31961058]]


In [24]:
t_3 = np.trunc(r_3)
print(t_3)

[[0.]
 [0.]]


In [25]:
f_3 = np.fix(r_3)
print(f_3)

[[0.]
 [0.]]


In [27]:
fl_3 = np.floor(r_3)
print(fl_3)

[[0.]
 [0.]]


In [28]:
c_3 = np.ceil(r_3)
print(c_3)

[[1.]
 [1.]]


In [32]:
ro_3 = np.round(r_3,2)
print(ro_3)

[[0.74]
 [0.32]]


## Cumulative Operations

In [33]:
print(r_4)

[[28 89 88 84 54]
 [77 25 59 59 56]
 [79 42 63 24 38]
 [57 82 77 77 63]]


In [34]:
print(np.sum(r_4))

1221


In [35]:
print(np.sum(r_4, axis=0))

[241 238 287 244 211]


In [36]:
print(np.sum(r_4, axis=1))

[343 276 246 356]


In [38]:
print(np.cumsum(r_4))

[  28  117  205  289  343  420  445  504  563  619  698  740  803  827
  865  922 1004 1081 1158 1221]


In [39]:
print(np.cumsum(r_4, axis = 0))

[[ 28  89  88  84  54]
 [105 114 147 143 110]
 [184 156 210 167 148]
 [241 238 287 244 211]]


## Grocery Problem

In [40]:
bag_1 = np.array([2,3,4,0])
bag_2 = np.array([4,0,1,2])
print(bag_1)
print(bag_2)

[2 3 4 0]
[4 0 1 2]


In [41]:
added_b1 = np.sum(bag_1)
added_b2 = np.sum(bag_2)
print(f"The first bag contains {added_b1} items, and the second bag contains {added_b2} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [42]:
#There are __ vegetables, __ fruits, __ boxes
# of snacks, and __ beverages in the two grocery bags

In [44]:
total = bag_1 + bag_2
print(f"The are {total[0]} vegies, {total[1]} fruits, {total[2]} boxes of snacks, and {total[3]} beverages in the two grocery bags")

The are 6 vegies, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags


## Teamwork

In [ ]:
#Ali reported knocking on 5 doors on Monday, 4 on Tuesday, 6 on Wednesday, 4 on
# Thursday, and 2 on Friday

In [45]:
ali = np.array([5,4,6,4,2])
print(ali)

[5 4 6 4 2]


In [46]:
# Ben missed Monday because he was out of town. He reported knocking on 5 on
# Tuesday, 5 on Wednesday, 3 on Thursday, and 4 on Friday

In [47]:
ben = np.array([0,5,5,3,4])
print(ben)

[0 5 5 3 4]


In [48]:
# Carla reported knocking on 3 doors on Monday, 6 on Tuesday, 3 on Thursday, and 4
# on Friday. She was sick on Wednesday so missed that day

In [50]:
carla = np.array([3,6,0,3,4])
print(carla)

[3 6 0 3 4]


In [51]:
all_knocks = np.array([ali,ben,carla])
print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [52]:
print(np.sum(all_knocks))

54


In [53]:
daily_knock = np.sum(all_knocks,axis=0)
print(daily_knock)

[ 8 15 11 10 10]


In [54]:
roll_knock = np.cumsum(daily_knock)
print(roll_knock)

[ 8 23 34 44 54]


In [56]:
r_votes = roll_knock * 0.5
print(r_votes)

[ 4.  11.5 17.  22.  27. ]
